[package]
name = "warp-on-fly"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
warp = "0.3.7"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

